/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "go.bytebuilders.dev/license-proxyserver/apis/proxyserver/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	testing "k8s.io/client-go/testing"
)

// FakeLicenseRequests implements LicenseRequestInterface
type FakeLicenseRequests struct {
	Fake *FakeProxyserverV1alpha1
}

var licenserequestsResource = v1alpha1.SchemeGroupVersion.WithResource("licenserequests")

var licenserequestsKind = v1alpha1.SchemeGroupVersion.WithKind("LicenseRequest")

// Create takes the representation of a licenseRequest and creates it.  Returns the server's representation of the licenseRequest, and an error, if there is any.
func (c *FakeLicenseRequests) Create(ctx context.Context, licenseRequest *v1alpha1.LicenseRequest, opts v1.CreateOptions) (result *v1alpha1.LicenseRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(licenserequestsResource, licenseRequest), &v1alpha1.LicenseRequest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LicenseRequest), err
}
